name: Deploy API

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

env:
  DEFAULT_DIR: ./lambdas
  AWS_REGION: eu-west-3
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: ${{ env.DEFAULT_DIR }}/yarn.lock

      - name: Install
        working-directory: ${{ env.DEFAULT_DIR }}
        run: yarn install

      - name: Build Api Lambda
        working-directory: ${{ env.DEFAULT_DIR }}
        run: npm run build:api

      - name: Build Seleccionadora Lambda
        working-directory: ${{ env.DEFAULT_DIR }}
        run: npm run build:seleccionadora

      - name: Zip Api Lambda Files
        uses: vimtor/action-zip@v1
        with:
          files: ${{ env.DEFAULT_DIR }}/dist/api/main.js
          dest: api-lambda.zip

      - name: Zip Seleccionadora Lambda Files
        uses: vimtor/action-zip@v1
        with:
          files: ${{ env.DEFAULT_DIR }}/dist/seleccionadora/main.js
          dest: seleccionadora-lambda.zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Api Lambda
        run: |
          aws lambda update-function-code --function-name softtek-training-dev-lmb-api --zip-file fileb://api-lambda.zip --region ${AWS_REGION}
          sleep 1
          echo "Published new version of the Api lambda function." >> $GITHUB_STEP_SUMMARY

      - name: Deploy Seleccionadora Lambda
        run: |
          aws lambda update-function-code --function-name softtek-training-dev-lmb-seleccionadora --zip-file fileb://seleccionadora-lambda.zip --region ${AWS_REGION}
          sleep 1
          echo "Published new version of the Seleccionadora lambda function." >> $GITHUB_STEP_SUMMARY
